server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hubspot_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

hubspot:
  client-id: ${HUBSPOT_CLIENT_ID}
  client-secret: ${HUBSPOT_CLIENT_SECRET}
  redirect-uri: ${HUBSPOT_REDIRECT_URI}
  webhook-secret: ${HUBSPOT_WEBHOOK_SECRET}

